version: '3.8'
services:
 ftp_server:
  image: stilliard/pure-ftpd
  container_name: ftp_server
  ports:
   - '21:21'
   - '30000-30009:30000-30009'
  volumes:
   - storage:/home/<LOGIN>
   - user_data:/etc/pure-ftpd/passwd
   - /home/opti/ftp/private:/etc/ssl/private
  environment:
   PUBLICHOST: "localhost"
   FTP_USER_NAME: "<LOGIN>"
   FTP_USER_PASS: "<PASSWORD>"
   FTP_USER_HOME: /home/<LOGIN>
   ADDED_FLAGS: "--tls=2 -d -d"
  restart: always
volumes:
 storage:
 user_data: