version: '3.8'
services:
 seq:
  image: datalust/seq
  container_name: seq
  ports:
   - '5444:80'
   - '5341:5341'
  volumes:
   - seq_storage:/data
  env_file:
   - seq-env.list
  restart: always
volumes:
 seq_storage: