apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-deployment
  labels:
    component: opti-cc
spec:
  replicas: 1
  selector:
    matchLabels:
      component: opti-cc
  template:
    metadata:
      labels:
        component: opti-cc
    spec:
      containers:
        - name: compressionchecker
          image: yoyrandao/opti-cc
          imagePullPolicy: Always
          ports:
            - containerPort: 5555
          volumeMounts:
              - name: config-secret
                mountPath: /app/secrets
                readOnly: true
      imagePullSecrets:
        - name: registry-key
      volumes:
        - name: config-secret
          secret:
            secretName: cc-appsettings