apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-deployment
  labels:
    app: opti-cc
spec:
  replicas: 1
  selector:
    matchLabels:
      component: opti-cc
  template:
    metadata:
      labels:
        component: opti-cc
    spec:
      containers:
        - name: compressionchecker
          image: yoyrandao/opti-cc
          imagePullPolicy: Always
          ports:
            - containerPort: 5555