apiVersion: v1
kind: Service
metadata:
  name: syncgateway-balancer
spec:
  type: LoadBalancer
  selector:
    component: opti-syncgateway
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000