version: '3.8'
services:
  opti_db:
    container_name: common_database
    image: 'crunchydata/crunchy-postgres:centos7-11.4-2.4.1'
    hostname: opti-db-ts
    env_file:
      - pg-env.list
    volumes:
      - db_data:/pgdata
      - ./scripts:/home/temp/scripts
    ports:
      - 5432:5432
    restart: always
volumes:
  db_data: