name: Gated

on:
  push:
    branches: [ pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v2
    
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
  
#     - name: dockerhub login
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
#     - name: setup docker buildx
#       id: buildx
#       uses: docker/setup-buildx-action@v1.1.1
      
    - name: build&push syncgateway image
      id: syncgateway_build_push
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: yoyrandao/opti-syncgateway
        tags: latest, $IMAGE_TAG
        registry: docker.io
        directory: ./src/
        dockerfile: ./src/backend/SyncGateway/Dockerfile
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
#     - name: build&push syncgateway image
#       id: syncgateway_build_push
#       uses: docker/build-push-action@v2.3.0
#       with:
#         context: ./src/
#         file: ./src/backend/SyncGateway/Dockerfile
#         push: true
#         tags: yoyrandao/opti-syncgateway:latest,yoyrandao/opti-syncgateway:$IMAGE_TAG
#         tagging: true
      
    
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
