name: Gated

on:
  push:
    branches: [ pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
  
    - name: dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: setup docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1.1.1
      
    - name: build&push syncgateway image
      id: syncgateway_build_push
      uses: docker/build-push-action@v2.3.0
      with:
        context: ./src/backend/SyncGateway/
        file: ./src/backend/SyncGateway/Dockerfile
        push: true
        tags: yoyrandao/opti-syncgateway:latest,yoyrandao/opti-syncgateway:${GITHUB_SHA:10}
      
    
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
